### ISSUE TITLE
Plog: Creation of a variable through json doesn't require a proposition. This creates confusion. 

### ISSUE THREAD

**Issue by ourmoa** [ourstudio-se/puan-python#53]
Restrict creation of variables through json to only be allowed as part of a proposition. 

E.g. restrict: {'type':'variable', 'bounds': {'lower':-10, 'upper': 10}, 'id': 'x'}

only allow 
{'propositions': [{'type':'variable', 'bounds': {'lower':-10, 'upper': 10}, 'id': 'x'}], "type": "All/Any/Xor..."}

**Comment by znittzel** [comment]
Closing because of new decision to allow creating variable using `from_json`
