### ISSUE TITLE
Possible to construct circular dependencies in models if not created through dict

### ISSUE THREAD

**Issue by ourmoa** [ourstudio-se/puan-python#71]
This model should not be possible to create
`model = cc.StingyConfigurator(
        pg.All(*"AB"),
        pg.AtMost(2, ["x", "y", "z"], variable="A"),
        pg.All(*"gef", variable="B"),
        pg.All(*"Abc", variable="g"))`
Add a validation function on the model, do not forget to include this on every plog model, not just the StingyConfigurator

**Comment by znittzel** [comment]
We choose to allow constructing models with circular dependencies since we favor speed over user friendly api's. To be consistent, we change the `puan.logic.plog.from_dict` function instead to allow circular dependencies
